#!/bin/bash
if [ -e student-record.c ]; then
	if [ -x student-record.c ]; then
		if [ -e records.txt ]; then
			if [ -f records.txt ]; then
				entries=$(cat records.txt)
				i=0
				gcc -o student student-record.c
				for entry in $entries
				do
					if [ $i -eq 0 ]; then
						./student -f database -c $entry
					else
						./student -f database -a $entry
					fi
					if [ ! $? -eq 0 ]; then
						echo "student-record.c ha fallado"
						exit 1
					fi
					i=$((i+1))
				done
				./student -f database -l
				if [ ! $? -eq 0 ]; then
						echo "student-record.c ha fallado"
						exit 1
				fi
				xxd database
				for entry in $entries
				do
					./student -f database -q -n $(cut -d ':' -f2<<<$entry)
					if [ ! $? -eq 0 ]; then
						echo "student-record.c ha fallado"
						exit 1
					fi
				done
				
			else	
				echo "records.txt no es un fichero regular"
			fi
		else
			echo "records.txt no existe"
		fi
	else
		echo "student-record no es ejecutable"
	fi
else
	echo "student-record no existe"
fi
